### PR TITLE
DBAAS-2387: Added createTable function

### PR DESCRIPTION
**Pull request by Ben-Epstein**
Added createTable function to allow the user to create a table from the dataframe schema so they don't need to do this in SQL.

Also added a replaceDataframeSchema function for insert/upsert/update functions as per Murray's comment, in case the user has mixed case column names.

### CODE REVIEW

**Review by njnygaard — APPROVED** [review]

**Review by bklo94 — APPROVED** [review]

**Comment by agoldfain-sm** [comment]
please add unit tests for new function, other than that looks good

**Comment by troysplice** [comment]
@Ben-Epstein this has 2 approver LGTM.

**Comment by Ben-Epstein** [comment]
@troysplice I think we should have unit tests for this before merging as Andrei suggested. I've added Amrit and assigned him to create a test for the function.

**Comment by abaveja313** [comment]
I have added 26 unit tests that verify the functionality of each function in pysplice. If it looks good, let me know if we can merge. @agoldfain-sm @Ben-Epstein @troysplice

**Review by Ben-Epstein — COMMENTED** [review]
Amrit, why are entire files being deleted and added here? Did you pull from master before making your changes? There are conflicts in the branch.

**Comment by abaveja313** [comment]
@Ben-Epstein I did pull from master before making my changes. On Monday I spoke with @agoldfain-sm and it seemed prudent to separate the tests into a tests/ directory, so we can easily run unit tests during CI. Since these unit tests haven't been updated since my first week last summer, I felt that the code could be made more clear by renaming certain test classes, adding functions etc. This is why it seems like files were deleted-- the code is intact, it is simply refactored. No changes were made to any code that is currently in use (e.g. pysplicectx). I think the only file that is conflicting is the .gitignore, which I can resolve when we merge.

**Pull request merged**
