### PR TITLE
DB-10880 eNSDS Transaction Support

### PR DESCRIPTION
**Pull request by jpanko1**
## Description
Enable transactions in eNSDS with support for commit, rollback, and savepoints.

## Motivation and Context
https://splicemachine.atlassian.net/browse/DB-10880

Added these methods, which function the same as the corresponding functions in the JDBC Connection object:

setAutoCommitOn()
setAutoCommitOff()

commit()
rollback()
rollback(savepoint)
setSavepoint()
setSavepoint(name)
releaseSavepoint(savepoint)

autoCommitting(): Boolean -- true when auto-commit is on
transactional(): Boolean -- true when auto-commit is off

Auto-commit on is the default. When auto-commit is on, eNSDS will behave the same as previously.

## Dependencies
Depends on spliceengine PR: https://github.com/splicemachine/spliceengine/pull/5322

## How Has This Been Tested?
Test by calling setAutoCommitOff and then performing one or more actions with eNSDS. Before committing, the results of the actions won't be visible from a separate connection which is outside of the eNSDS transaction, but they will be visible with eNSDS. Call commit to commit, or call rollback to wipe out the changes before committing. Savepoints are also available. Call setAutoCommitOn to return to auto-commit mode.

## Screenshots (if appropriate):
N/A

### CODE REVIEW

**Comment by Ben-Epstein** [comment]
@jpanko1 what database build is this included in? We cannot merge until that is available

**Review by myles-novick — APPROVED** [review]

**Review by Ben-Epstein — CHANGES_REQUESTED** [review]
Need to know DB version requirements before merging

**Comment by jpanko1** [comment]
> Need to know DB version requirements before merging

It's still being reviewed for a DB build in PR https://github.com/splicemachine/spliceengine/pull/5322

**Comment by jpanko1** [comment]
> > Need to know DB version requirements before merging
> 
> It's still being reviewed for a DB build in PR [splicemachine/spliceengine#5322](https://github.com/splicemachine/spliceengine/pull/5322)

It went into the DB 2007 build.

**Comment by jpanko1** [comment]
I also added in this code push the fix Jack needed for eNSDS to work in Databricks.

**Review by Ben-Epstein — APPROVED** [review]

**Pull request merged**
