### PR TITLE
DB-7600:Pysplice Methods need sync-up with Scala methods

### PR DESCRIPTION
**Pull request by liprais**

### CODE REVIEW

**Comment by liprais** [comment]
this pull request adds the following functions to pysplice:
execute
executeUpdate
internalDf
truncate
analyzeSchema
analyzeTable
also fixes a problem that pysplice will always create a new local spark session when starting up

**Review by MurrayBrown — APPROVED** [review]
I love it, Xiao!

**Comment by MurrayBrown** [comment]
The fix for spinning up extra spark contexts may actually address the memory problems we were seeing with python and scala last September - i'll be interested to see this in action!

**Review by Ben-Epstein — APPROVED** [review]
Looks great

**Pull request merged**
